spring:
  application:
    name: protomil-core
  
  datasource:
    url: jdbc:postgresql://localhost:5432/protomil_db
    username: protomil_user
    password: protomil_secure_pass_2024
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true

# Basic management endpoints (restrictive by default)
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: true

# AWS Configuration (empty by default)
aws:
  region: ${AWS_REGION:us-east-1}
  cognito:
    enabled: ${AWS_COGNITO_ENABLED:false}
    userPoolId: ${AWS_COGNITO_USER_POOL_ID:}
    clientId: ${AWS_COGNITO_CLIENT_ID:}

# Logging
logging:
  level:
    root: INFO
    com.protomil: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"