spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protomil_db
    username: protomil_user
    password: protomil_secure_pass_2024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

aws:
  cognito:
    enabled: true
    userPoolId: ${AWS_COGNITO_DEV_USER_POOL_ID:your-dev-pool-id}
    clientId: ${AWS_COGNITO_DEV_CLIENT_ID:your-dev-client-id}
    region: ${AWS_REGION:us-east-1}
  region: ${AWS_REGION:us-east-1}

# Enable all actuator endpoints for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.protomil: DEBUG
    org.springframework.security: DEBUG
    com.protomil.core.user: DEBUG
    software.amazon.awssdk: DEBUG