spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protomil_db
    username: protomil_user
    password: protomil_secure_pass_2024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration  # This is correct
    validate-on-migrate: true
    clean-disabled: true
  thymeleaf:
    cache: false # Disable caching for development
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  web:
    resources:
      add-mappings: true
  mvc:
    favicon:
      enabled: false
  task:
    scheduling:
      enabled: true
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100

aws:
  profile: ${AWS_PROFILE:protomil-dev}
  region: ${AWS_REGION:ap-south-1}
  cognito:
    enabled: true
    userPoolId: ${AWS_COGNITO_DEV_USER_POOL_ID:your-dev-pool-id}
    clientId: ${AWS_COGNITO_DEV_CLIENT_ID:your-dev-client-id}
    region: ${AWS_REGION:ap-south-1}
    authFlows:
      - ALLOW_ADMIN_USER_PASSWORD_AUTH
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    email:
      verificationRequired: true
      fromEmail: ${AWS_COGNITO_FROM_EMAIL:noreply@protomil.com}
      replyToEmail: ${AWS_COGNITO_REPLY_TO_EMAIL:support@protomil.com}
      verificationSubject: "Verify your Protomil account"
      verificationMessage: "Your verification code is {####}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.protomil: DEBUG
    org.springframework.security: DEBUG
    com.protomil.core.user: DEBUG
    software.amazon.awssdk: DEBUG
    software.amazon.awssdk.services.sso: INFO
    io.github.wimdeblauwe.htmx: DEBUG # Enable HTMX logging

htmx:
  enabled: true
  use-htmx-response-headers: true

protomil:
  security:
    jwt:
      secret: ${JWT_SECRET:protomil-dev-secret-key-for-development-only-change-in-production}
      access-token-expiration: 1800  # 30 minutes
      refresh-token-expiration: 7200  # 2 hours
      issuer: protomil-core
    cookies:
      secure: false  # Set to true in production with HTTPS
      same-site: Strict
      domain: ${COOKIE_DOMAIN:}
      path: /
  ui:
    dashboard:
      auto-refresh-interval: 300000  # 5 minutes
      widgets:
        enabled: true
        show-phase-info: true
      navigation:
        show-disabled-items: true
        show-tooltips: true
  user-status:
    sync:
      enabled: true
      daily-sync-times: ["06:00", "18:00"]  # 6 AM and 6 PM
      retry-attempts: 2
      retry-delay: 5000  # 5 seconds
      failure-status-after-retries: true
      block-login-on-sync-failure: true       # Alert after 7 days in pending status

    cognito:
      sync-on-login: true          # Validate status consistency on every login
      sync-on-status-change: true  # Auto-sync when status changes locally
      retry-attempts: 3            # Number of retry attempts for failed syncs
      retry-delay: 5000