# src/main/resources/application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protomil_db
    username: protomil_user
    password: protomil_secure_pass_2024

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false  # Allow clean in dev environment

logging:
  level:
    root: INFO
    com.protomil: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG