spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/protomil_db
    username: protomil_user
    password: protomil_secure_pass_2024
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

# Disable Cognito for local development
aws:
  cognito:
    enabled: false
    userPoolId: ""
    clientId: ""
  region: us-east-1

# Enable all actuator endpoints for dev
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.protomil: DEBUG
    org.springframework.security: DEBUG