spring:
  config:
    activate:
      on-profile: prod
  
  # Production database settings
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: false

# Production Management - Restricted endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway,metrics
  endpoint:
    health:
      show-details: when-authorized
  security:
    enabled: true

# AWS Configuration for Production
aws:
  cognito:
    enabled: true
    userPoolId: ${AWS_COGNITO_PROD_USER_POOL_ID}
    clientId: ${AWS_COGNITO_PROD_CLIENT_ID}
    region: ${AWS_REGION:us-east-1}

# Production Logging - Less verbose
logging:
  level:
    root: WARN
    com.protomil: INFO
    org.springframework.security: WARN